version: '3.8'

services:
  app:
    build: 
      context: .
      target: production
    container_name: devops-demo-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    networks:
      - devops-network
    restart: unless-stopped

networks:
  devops-network:
    driver: bridge
