name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes (opcional)
        run: |
          echo "Sem testes automatizados por enquanto"
          # npm test

      - name: Build da imagem Docker
        run: docker build -t minha-app .

      - name: Deploy via SSH (com Docker Compose)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/devops-projeto  
            git pull
            docker-compose down
            docker-compose up -d --build
